Provisioned Terraform configuration, add Infracost pre-commit hook to check forecast

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -72,6 +72,21 @@ fi
 
 echo "✅ Terraform validate passed."
 
+echo "🔃 Running Infracost to check cost forecast ..."
+json_output=$(infracost breakdown --path . --format json)
+total=$(jq -r '.totalMonthlyCost' <<<"$json_output")
+if ! [[ $total =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
+    echo "❌ Error: totalMonthlyCost is not a valid number: '$total'" >&2
+    exit 1
+fi
+
+if awk "BEGIN { exit !($total > 100) }"; then
+    echo "❌ Error: totalMonthlyCost ($total) exceeds 100" >&2
+    exit 1
+fi
+
+echo "✅ Infracost completed. Cost forecast is within the limits, totalMonthlyCost is $total"
+
 echo "🔃 Moving back to root directory ..."
 cd .. || exit 1
 
